"""Generate constexpr current-object field descriptors from canonical JSON data."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def render(value: object) -> str:
    if not isinstance(value, dict) or set(value) != {"schema_version", "sbnk_fields"}:
        raise ValueError("field layout has unknown or missing top-level keys")
    if value["schema_version"] != "1.0":
        raise ValueError("unsupported field-layout schema")
    fields = value["sbnk_fields"]
    if not isinstance(fields, list):
        raise ValueError("sbnk_fields must be a list")
    rows: list[str] = []
    seen: set[str] = set()
    for field in fields:
        if not isinstance(field, dict) or set(field) != {"name", "offset", "signed", "width"}:
            raise ValueError("field descriptor has unknown or missing keys")
        name = field["name"]
        offset = field["offset"]
        width = field["width"]
        signed = field["signed"]
        if not isinstance(name, str) or name in seen:
            raise ValueError("field names must be unique strings")
        if not isinstance(offset, int) or not isinstance(width, int) or width not in {1, 2, 4}:
            raise ValueError(f"invalid location for {name}")
        if not isinstance(signed, bool) or (signed and width != 1):
            raise ValueError(f"invalid signedness for {name}")
        seen.add(name)
        rows.append(
            f'    NumericFieldDescriptor{{"{name}", 0x{offset:03x}U, {width}U, '
            f'{str(signed).lower()}}},'
        )
    return "\n".join(
        [
            "// Generated by cpp/tools/generate_current_fields.py. Do not edit.",
            "#pragma once",
            "",
            "#include <array>",
            "#include <cstdint>",
            "#include <string_view>",
            "",
            "namespace axk::generated {",
            "",
            "struct NumericFieldDescriptor {",
            "  std::string_view name;",
            "  std::uint32_t offset;",
            "  std::uint8_t width;",
            "  bool is_signed;",
            "};",
            "",
            "inline constexpr std::array sbnk_numeric_fields{",
            *rows,
            "};",
            "",
            "}  // namespace axk::generated",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("data", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    value = json.loads(args.data.read_text(encoding="utf-8"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(value), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
