"""Generate constexpr C++ effect tables from the versioned JSON dataset."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def quoted(value: object) -> str:
    if not isinstance(value, str):
        raise ValueError("effect string field has invalid type")
    return json.dumps(value, ensure_ascii=True)


def render(value: object) -> str:
    if not isinstance(value, dict) or set(value) != {
        "schema_version",
        "effect_types",
        "effect_parameters",
        "enum_value_tables",
        "known_display_values",
    }:
        raise ValueError("effect data has unknown or missing top-level keys")
    if value["schema_version"] != "1.0":
        raise ValueError("unsupported effect-data schema")
    types = value["effect_types"]
    parameters = value["effect_parameters"]
    enum_tables = value["enum_value_tables"]
    known = value["known_display_values"]
    if not all(isinstance(item, list) for item in (types, parameters, enum_tables, known)):
        raise ValueError("effect-data collections must be arrays")
    out = [
        "// Generated by cpp/tools/generate_current_effects.py. Do not edit.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace axk::generated {",
        "",
        "struct EffectTypeData { std::uint16_t raw_type; std::uint16_t printed_number; std::string_view printed_label; std::string_view ui_label; bool validated; };",
        "struct EffectParameterData { std::uint16_t raw_type; std::uint8_t parameter_number; std::string_view effect_label; std::string_view parameter_label; std::string_view range_text; std::string_view raw_min; std::string_view raw_max; std::string_view raw_interval; std::string_view raw_scaler; std::string_view raw_shift; std::string_view value_source; std::string_view table_source; };",
        "struct EffectEnumValue { std::string_view table; std::uint16_t index; std::string_view label; };",
        "struct KnownEffectDisplay { std::uint16_t raw_type; std::uint8_t parameter_number; std::uint8_t raw_value; std::string_view display; };",
        "",
        f"inline constexpr std::array<EffectTypeData, {len(types)}> effect_types{{",
    ]
    for raw in types:
        if not isinstance(raw, dict):
            raise ValueError("effect type row must be an object")
        row = raw
        out.append(
            "    EffectTypeData{" + ", ".join(
                (
                    str(int(row["raw_type"])),
                    str(int(row["printed_number"])),
                    quoted(row["printed_label"]),
                    quoted(row["ui_label"]),
                    "true" if row["validated"] else "false",
                )
            ) + "},"
        )
    out.extend(
        [
            "};",
            "",
            f"inline constexpr std::array<EffectParameterData, {len(parameters)}> effect_parameters{{",
        ]
    )
    for raw in parameters:
        if not isinstance(raw, dict):
            raise ValueError("effect parameter row must be an object")
        row = raw
        out.append(
            "    EffectParameterData{" + ", ".join(
                (
                    str(int(row["raw_type"])),
                    str(int(row["parameter_number"])),
                    quoted(row["effect_label"]),
                    quoted(row["parameter_label"]),
                    quoted(row["parameter_range_text"]),
                    quoted(row["raw_min"]),
                    quoted(row["raw_max"]),
                    quoted(row["raw_interval"]),
                    quoted(row["raw_scaler"]),
                    quoted(row["raw_shift"]),
                    quoted(row["value_label_source"]),
                    quoted(row["table_source"]),
                )
            ) + "},"
        )
    enum_value_count = sum(
        len(raw["values"])
        for raw in enum_tables
        if isinstance(raw, dict) and isinstance(raw.get("values"), list)
    )
    out.extend(
        [
            "};",
            "",
            f"inline constexpr std::array<EffectEnumValue, {enum_value_count}> effect_enum_values{{",
        ]
    )
    for raw in enum_tables:
        if not isinstance(raw, dict) or not isinstance(raw.get("values"), list):
            raise ValueError("effect enum row must contain an array")
        for index, label in enumerate(raw["values"]):
            out.append(
                f"    EffectEnumValue{{{quoted(raw['name'])}, {index}, {quoted(label)}}},"
            )
    out.extend(
        [
            "};",
            "",
            f"inline constexpr std::array<KnownEffectDisplay, {len(known)}> known_effect_displays{{",
        ]
    )
    for raw in known:
        if not isinstance(raw, dict):
            raise ValueError("known display row must be an object")
        out.append(
            "    KnownEffectDisplay{" + ", ".join(
                (
                    str(int(raw["raw_type"])),
                    str(int(raw["parameter_number"])),
                    str(int(raw["raw_value"])),
                    quoted(raw["display"]),
                )
            ) + "},"
        )
    out.extend(["};", "", "}  // namespace axk::generated", ""])
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("data", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    value: Any = json.loads(args.data.read_text(encoding="utf-8"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(value), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
