"""Generate constexpr current-object label tables from canonical JSON data."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def _identifier(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")


def render(value: object) -> str:
    if not isinstance(value, dict) or set(value) != {"schema_version", "tables"}:
        raise ValueError("lookup data has unknown or missing top-level keys")
    if value["schema_version"] != "1.0" or not isinstance(value["tables"], list):
        raise ValueError("unsupported lookup-data schema")
    output = [
        "// Generated by cpp/tools/generate_current_lookups.py. Do not edit.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace axk::generated {",
        "",
        "struct LookupEntry { std::int32_t key; std::string_view label; };",
        "",
    ]
    seen: set[str] = set()
    identifiers: list[str] = []
    for table in value["tables"]:
        if not isinstance(table, dict) or set(table) != {"name", "values"}:
            raise ValueError("lookup table has unknown or missing keys")
        name = table["name"]
        values = table["values"]
        if not isinstance(name, str) or not isinstance(values, list):
            raise ValueError("lookup name and values have invalid types")
        identifier = _identifier(name)
        if not identifier or identifier in seen:
            raise ValueError("lookup names must produce unique identifiers")
        seen.add(identifier)
        identifiers.append(identifier)
        output.append(f"inline constexpr std::array {identifier}{{")
        for row in values:
            if not isinstance(row, dict) or set(row) != {"key", "label"}:
                raise ValueError(f"invalid row in {name}")
            key = row["key"]
            label = row["label"]
            if not isinstance(key, int) or not isinstance(label, str):
                raise ValueError(f"invalid row types in {name}")
            escaped = json.dumps(label, ensure_ascii=True)
            output.append(f"    LookupEntry{{{key}, {escaped}}},")
        output.extend(["};", ""])
    output.extend(
        [
            "enum class LookupId : std::uint8_t {",
            *[f"  {identifier}," for identifier in identifiers],
            "};",
            "",
            "template <std::size_t Size>",
            "constexpr std::string_view find_label(",
            "    const std::array<LookupEntry, Size>& table, std::int32_t key) noexcept {",
            "  for (const auto& row : table) if (row.key == key) return row.label;",
            "  return {};",
            "}",
            "",
            "constexpr std::string_view lookup(LookupId table, std::int32_t key) noexcept {",
            "  switch (table) {",
            *[
                f"    case LookupId::{identifier}: return find_label({identifier}, key);"
                for identifier in identifiers
            ],
            "  }",
            "  return {};",
            "}",
            "",
        ]
    )
    output.extend(["}  // namespace axk::generated", ""])
    return "\n".join(output)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("data", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    value = json.loads(args.data.read_text(encoding="utf-8"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(value), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
