#include "operation_registry_floppy.hpp"

namespace axk::app {
const std::array<OperationDescriptor, 4U> &floppy_import_descriptors() {
    static const std::array descriptors{OperationDescriptor{"images.floppy_import.inspect",
                                                            {},
                                                            HttpMethod::post,
                                                            "/api/v1/floppy-import-inspections",
                                                            ExecutionMode::job,
                                                            {},
                                                            "FloppyImportInspectionRequest",
                                                            "FloppyImportInspection",
                                                            OperationClass::read,
                                                            false,
                                                            false},
                                        OperationDescriptor{"images.floppy_import.release",
                                                            {},
                                                            HttpMethod::post,
                                                            "/api/v1/floppy-import-inspections/release",
                                                            ExecutionMode::request,
                                                            {},
                                                            "FloppyImportInspectionReleaseRequest",
                                                            "PlanReleaseResult",
                                                            OperationClass::read,
                                                            false,
                                                            false},
                                        OperationDescriptor{"images.floppy_import.plan",
                                                            {},
                                                            HttpMethod::post,
                                                            "/api/v1/image-floppy-import-plans",
                                                            ExecutionMode::request,
                                                            {},
                                                            "ImageFloppyImportPlanRequest",
                                                            "ImageSessionPackageImportPlan",
                                                            OperationClass::read,
                                                            false,
                                                            false},
                                        OperationDescriptor{"images.floppy_import",
                                                            {},
                                                            HttpMethod::post,
                                                            "/api/v1/image-floppy-imports",
                                                            ExecutionMode::job,
                                                            {},
                                                            "PackageImportRequest",
                                                            "ImageSessionPackageImportResult",
                                                            OperationClass::write,
                                                            true,
                                                            false}};
    return descriptors;
}
} // namespace axk::app
