#include "operation_registry_capacity.hpp"

namespace axk::app {
const std::array<OperationDescriptor, 5U> &capacity_descriptors() {
    static const std::array descriptors{
        OperationDescriptor{"images.volume_capacity.inspect",
                            "axklib capacity volume",
                            HttpMethod::post,
                            "/api/v1/image-volume-capacity-inspections",
                            ExecutionMode::request,
                            {},
                            "ImageVolumeCapacityInspectionRequest",
                            "ImageVolumeCapacityInspection",
                            OperationClass::read,
                            false,
                            true},
        OperationDescriptor{"images.alter.inspect",
                            {},
                            HttpMethod::post,
                            "/api/v1/image-session-alteration-inspections",
                            ExecutionMode::request,
                            {},
                            "ImageSessionAlterationRequest",
                            "ImageSessionAlterationInspection",
                            OperationClass::read,
                            false,
                            false},
        OperationDescriptor{"images.filesystem.edit.inspect",
                            {},
                            HttpMethod::post,
                            "/api/v1/image-filesystem-edit-inspections",
                            ExecutionMode::request,
                            {},
                            "ImageFilesystemEditRequest",
                            "ImageSessionAlterationInspection",
                            OperationClass::read,
                            false,
                            false},
        OperationDescriptor{"images.programs.generate.prepare",
                            {},
                            HttpMethod::post,
                            "/api/v1/image-program-generation-preparations",
                            ExecutionMode::request,
                            {},
                            "ImageProgramGenerationRequest",
                            "ImageSessionAlterationRequest",
                            OperationClass::read,
                            false,
                            false},
        OperationDescriptor{"images.placement.repair.prepare",
                            {},
                            HttpMethod::post,
                            "/api/v1/image-placement-repair-preparations",
                            ExecutionMode::request,
                            {},
                            "ImagePlacementRepairRequest",
                            "ImageSessionAlterationRequest",
                            OperationClass::read,
                            false,
                            false},
    };
    return descriptors;
}
} // namespace axk::app
