"""Generate constexpr C++ effect tables from the versioned JSON dataset."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path
from typing import Any


def quoted(value: object) -> str:
    if not isinstance(value, str):
        raise ValueError("effect string field has invalid type")
    return json.dumps(value, ensure_ascii=True)


def render_write_types(value: object) -> list[str]:
    if not isinstance(value, list) or len(value) != 97:
        raise ValueError("write tables must cover all 97 ordinary types")
    out = [
        "struct EffectWriteParameterData { std::uint8_t kind; std::uint16_t minimum; std::uint16_t maximum; };",
        "struct EffectWriteTypeData { std::uint8_t legacy_type; std::array<std::uint16_t, 16> reset_words; std::array<EffectWriteParameterData, 16> parameters; };",
        "inline constexpr std::array<EffectWriteTypeData, 97> effect_write_types{",
    ]
    kinds = {"stored_value": 0, "control_action": 1, "unused": 2}
    for raw, row in enumerate(value):
        if not isinstance(row, dict) or set(row) != {"raw_type", "legacy_type", "reset_words", "parameters"}:
            raise ValueError("write type has unknown or missing keys")
        if type(row["raw_type"]) is not int or row["raw_type"] != raw:
            raise ValueError("write types must be ordered and unique")
        if type(row["legacy_type"]) is not int or row["legacy_type"] != (raw if raw <= 54 else 0):
            raise ValueError("invalid legacy type projection")
        words, parameters = row["reset_words"], row["parameters"]
        if not isinstance(words, list) or len(words) != 16 or any(type(word) is not int or not 0 <= word <= 65535 for word in words):
            raise ValueError("reset vector must contain exactly sixteen u16 words")
        if not isinstance(parameters, list) or len(parameters) != 16:
            raise ValueError("write type must describe sixteen physical parameters")
        rendered = []
        for word, parameter in zip(words, parameters, strict=True):
            if not isinstance(parameter, dict) or set(parameter) != {"kind", "minimum", "maximum"}:
                raise ValueError("write parameter has unknown or missing keys")
            kind = parameter["kind"]
            minimum, maximum = parameter["minimum"], parameter["maximum"]
            if not isinstance(kind, str) or kind not in kinds or type(minimum) is not int or type(maximum) is not int or not 0 <= minimum <= maximum <= 65535:
                raise ValueError("invalid parameter write domain")
            if kind == "stored_value" and not minimum <= word <= maximum:
                raise ValueError("stored parameter default is outside its domain")
            rendered.append(f"EffectWriteParameterData{{{kinds[kind]}, {minimum}, {maximum}}}")
        out.append("    EffectWriteTypeData{" + str(row["legacy_type"]) + ", {" + ", ".join(map(str, words)) + "}, {" + ", ".join(rendered) + "}},")
    out.extend(["};", ""])
    return out


def render(value: object) -> str:
    if not isinstance(value, dict) or set(value) != {
        "schema_version",
        "effect_types",
        "effect_parameters",
        "enum_value_tables",
        "known_display_values",
        "write_types",
    }:
        raise ValueError("effect data has unknown or missing top-level keys")
    if value["schema_version"] != "1.0":
        raise ValueError("unsupported effect-data schema")
    types = value["effect_types"]
    parameters = value["effect_parameters"]
    enum_tables = value["enum_value_tables"]
    known = value["known_display_values"]
    if not all(isinstance(item, list) for item in (types, parameters, enum_tables, known)):
        raise ValueError("effect-data collections must be arrays")
    out = [
        "// Generated by tools/python/generate_current_effects.py. Do not edit.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace axk::generated {",
        "",
        "struct EffectTypeData { std::uint16_t raw_type; std::uint16_t printed_number; std::string_view printed_label; std::string_view ui_label; bool validated; };",
        "struct EffectParameterData { std::uint16_t raw_type; std::uint8_t parameter_number; std::string_view effect_label; std::string_view parameter_label; std::string_view range_text; std::string_view raw_min; std::string_view raw_max; std::string_view raw_interval; std::string_view raw_scaler; std::string_view raw_shift; std::string_view value_source; std::string_view table_source; };",
        "struct EffectEnumValue { std::string_view table; std::uint16_t index; std::string_view label; };",
        "struct KnownEffectDisplay { std::uint16_t raw_type; std::uint8_t parameter_number; std::uint16_t raw_value; std::string_view display; };",
        "",
        f"inline constexpr std::array<EffectTypeData, {len(types)}> effect_types{{",
    ]
    for raw in types:
        if not isinstance(raw, dict):
            raise ValueError("effect type row must be an object")
        row = raw
        out.append(
            "    EffectTypeData{" + ", ".join(
                (
                    str(int(row["raw_type"])),
                    str(int(row["printed_number"])),
                    quoted(row["printed_label"]),
                    quoted(row["ui_label"]),
                    "true" if row["validated"] else "false",
                )
            ) + "},"
        )
    out.extend(
        [
            "};",
            "",
            f"inline constexpr std::array<EffectParameterData, {len(parameters)}> effect_parameters{{",
        ]
    )
    for raw in parameters:
        if not isinstance(raw, dict):
            raise ValueError("effect parameter row must be an object")
        row = raw
        out.append(
            "    EffectParameterData{" + ", ".join(
                (
                    str(int(row["raw_type"])),
                    str(int(row["parameter_number"])),
                    quoted(row["effect_label"]),
                    quoted(row["parameter_label"]),
                    quoted(row["parameter_range_text"]),
                    quoted(row["raw_min"]),
                    quoted(row["raw_max"]),
                    quoted(row["raw_interval"]),
                    quoted(row["raw_scaler"]),
                    quoted(row["raw_shift"]),
                    quoted(row["value_label_source"]),
                    quoted(row["table_source"]),
                )
            ) + "},"
        )
    enum_value_count = sum(
        len(raw["values"])
        for raw in enum_tables
        if isinstance(raw, dict) and isinstance(raw.get("values"), list)
    )
    out.extend(
        [
            "};",
            "",
            f"inline constexpr std::array<EffectEnumValue, {enum_value_count}> effect_enum_values{{",
        ]
    )
    for raw in enum_tables:
        if not isinstance(raw, dict) or not isinstance(raw.get("values"), list):
            raise ValueError("effect enum row must contain an array")
        for index, label in enumerate(raw["values"]):
            out.append(
                f"    EffectEnumValue{{{quoted(raw['name'])}, {index}, {quoted(label)}}},"
            )
    out.extend(
        [
            "};",
            "",
            f"inline constexpr std::array<KnownEffectDisplay, {len(known)}> known_effect_displays{{",
        ]
    )
    for raw in known:
        if not isinstance(raw, dict):
            raise ValueError("known display row must be an object")
        out.append(
            "    KnownEffectDisplay{" + ", ".join(
                (
                    str(int(raw["raw_type"])),
                    str(int(raw["parameter_number"])),
                    str(int(raw["raw_value"])),
                    quoted(raw["display"]),
                )
            ) + "},"
        )
    out.extend(["};", ""])
    out.extend(render_write_types(value["write_types"]))
    out.extend(["}  // namespace axk::generated", ""])
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("data", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    value: Any = json.loads(args.data.read_text(encoding="utf-8"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(value), encoding="utf-8")
    style = Path(__file__).resolve().parents[2] / ".clang-format"
    subprocess.run(["clang-format", f"--style=file:{style}", "-i", str(args.output)], check=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
