function(axk_enable_coverage target)
  if(NOT AXK_ENABLE_COVERAGE)
    return()
  endif()
  if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(${target} PRIVATE --coverage -O0 -g)
    target_link_options(${target} PRIVATE --coverage)
  else()
    message(FATAL_ERROR "AXK_ENABLE_COVERAGE requires GCC or Clang")
  endif()
endfunction()
