if(NOT DEFINED AXK_ABI_MANIFEST OR NOT DEFINED AXK_ABI_OUTPUT_DIR)
  message(FATAL_ERROR "AXK_ABI_MANIFEST and AXK_ABI_OUTPUT_DIR are required")
endif()

file(STRINGS "${AXK_ABI_MANIFEST}" lines)
set(abi_node "")
set(abi_version "")
set(library "")
set(symbols "")
set(previous_symbol "")

foreach(line IN LISTS lines)
  string(STRIP "${line}" line)
  if(line STREQUAL "" OR line MATCHES "^#")
    continue()
  elseif(line MATCHES "^abi_node ([A-Z][A-Z0-9_]*_([0-9]+\\.[0-9]+))$")
    if(NOT abi_node STREQUAL "")
      message(FATAL_ERROR "duplicate abi_node in ${AXK_ABI_MANIFEST}")
    endif()
    set(abi_node "${CMAKE_MATCH_1}")
    set(abi_version "${CMAKE_MATCH_2}")
  elseif(line MATCHES "^library ([A-Za-z][A-Za-z0-9_]*)$")
    if(NOT library STREQUAL "")
      message(FATAL_ERROR "duplicate library in ${AXK_ABI_MANIFEST}")
    endif()
    set(library "${CMAKE_MATCH_1}")
  elseif(line MATCHES "^symbol (axk_[A-Za-z0-9_]+) ([0-9]+\\.[0-9]+) (active|deprecated)$")
    set(symbol "${CMAKE_MATCH_1}")
    set(introduced "${CMAKE_MATCH_2}")
    if(NOT introduced STREQUAL abi_version)
      message(FATAL_ERROR "unsupported introduction version ${introduced} for ${symbol}")
    endif()
    if(NOT previous_symbol STREQUAL "" AND NOT previous_symbol STRLESS symbol)
      message(FATAL_ERROR "symbols must be unique and lexicographically sorted: ${symbol}")
    endif()
    list(APPEND symbols "${symbol}")
    set(previous_symbol "${symbol}")
  else()
    message(FATAL_ERROR "invalid ABI manifest line: ${line}")
  endif()
endforeach()

if(abi_node STREQUAL "" OR library STREQUAL "" OR symbols STREQUAL "")
  message(FATAL_ERROR "ABI manifest requires abi_node, library, and at least one symbol")
endif()

file(MAKE_DIRECTORY "${AXK_ABI_OUTPUT_DIR}")
set(symbols_text "")
set(map_text "${abi_node} {\n  global:\n")
set(exports_text "")
set(def_text "LIBRARY ${library}\nEXPORTS\n")
foreach(symbol IN LISTS symbols)
  string(APPEND symbols_text "${symbol}\n")
  string(APPEND map_text "    ${symbol};\n")
  string(APPEND exports_text "_${symbol}\n")
  string(APPEND def_text "  ${symbol}\n")
endforeach()
string(APPEND map_text "  local: *;\n};\n")

file(WRITE "${AXK_ABI_OUTPUT_DIR}/axklib_c.symbols" "${symbols_text}")
file(WRITE "${AXK_ABI_OUTPUT_DIR}/axklib_c.map" "${map_text}")
file(WRITE "${AXK_ABI_OUTPUT_DIR}/axklib_c.exports" "${exports_text}")
file(WRITE "${AXK_ABI_OUTPUT_DIR}/axklib_c.def" "${def_text}")
